import { EventListener } from '../common/types';
import ValidationErrors from '../validation/ValidationErrors';
import { FormModelListenerArgsByEventName } from './types/FormModelListenerArgsByEventName';
import IFormService, { FormServiceEmptyState, FormServiceParams, FormServiceState, FormServiceListenerArgsByEventName } from './types/IFormService';
declare class FormService<TRecord extends Record<string, unknown>, TAvailableField extends keyof TRecord & string> implements IFormService<TRecord, TAvailableField> {
    validating: boolean;
    submitting: boolean;
    private eventEmitter;
    private errors;
    private warnings;
    private hiddenValidationFields;
    private changes;
    private fields;
    private partialErrorChecking;
    private partialErrorCheckingDefault;
    private submitAll;
    private initalizedState;
    constructor(fields?: TAvailableField[] | undefined);
    init({ fields, model, data, changes, warningsValidator, partialErrorChecking, submitAll }: FormServiceParams<TRecord, TAvailableField, FormModelListenerArgsByEventName<TRecord>>): Promise<void>;
    getAll(): FormServiceEmptyState<TRecord, TAvailableField> | FormServiceState<TRecord, TAvailableField>;
    updateField: <TField extends keyof TRecord & string>(field: TField, value: Element | TRecord[TField]) => Promise<void>;
    addChangeListener(func: EventListener<FormServiceListenerArgsByEventName<TRecord, TAvailableField>['update']>): void;
    removeChangeListener(func: (state: ReturnType<IFormService<TRecord, TAvailableField>['getAll']>) => void): void;
    removeAllListeners(): void;
    clearValidation: (fields: (keyof TRecord & string)[] | (keyof TRecord & string)) => void;
    clearError: (field: keyof TRecord & string) => void;
    validateField: <TField extends keyof TRecord & string>(field: TField, value: Element | TRecord[TField]) => Promise<void>;
    set(data: Partial<TRecord>, validate?: boolean): Promise<void>;
    submitData(data: Partial<TRecord>): Promise<Partial<TRecord> | undefined>;
    submit(): Promise<Partial<TRecord> | undefined>;
    clearFieldChanges(field: keyof TRecord & string): void;
    clearChanges: () => void;
    setPartialErrorChecking(value: boolean): void;
    getPartialErrorChecking(): boolean;
    validateForm: () => Promise<{
        errors: ValidationErrors<keyof TRecord & string> | null;
        warnings: ValidationErrors<keyof TRecord & string> | null;
    } | undefined>;
    private throttledValidateForm;
    private getFields;
    private isLoaded;
    private getChangesFields;
    private getDisplayedErrors;
    private setState;
    private onModelChange;
    private getData;
    private getChanges;
    private isDependentField;
    private runValidator;
    private getEmptyState;
}
export default FormService;
