import {Table} from 'ts-sql-query/Table';
import {DBConnection} from './MySqlPool';

const enum Gender {
  Male = 1,
  Female = 2
}

export class UserTable extends Table<DBConnection, 'TUser'> {
  id = this.autogeneratedPrimaryKey('id', 'int');
  name = this.column('name', 'string');
  surname = this.column('surname', 'string');
  phone = this.column('phone', 'string');
  age = this.column('age', 'int');
  gender = this.column<Gender>('gender', 'enum', 'Gender');

  constructor() {
    super('users');
  }
}

export const tUser = new UserTable();
